var hierarchy =
[
    [ "dg::AB< k, Vector >", "structdg_1_1_a_b.html", null ],
    [ "dg::ABS< T >", "structdg_1_1_a_b_s.html", null ],
    [ "dg::AbsMax< T >", "structdg_1_1_abs_max.html", null ],
    [ "dg::AbsMin< T >", "structdg_1_1_abs_min.html", null ],
    [ "dg::ArakawaX< Matrix, container >", "structdg_1_1_arakawa_x.html", null ],
    [ "dg::BathRZ", "structdg_1_1_bath_r_z.html", null ],
    [ "dg::CG< Vector >", "classdg_1_1_c_g.html", null ],
    [ "dg::CG< container >", "classdg_1_1_c_g.html", null ],
    [ "dg::CONSTANT", "structdg_1_1_c_o_n_s_t_a_n_t.html", null ],
    [ "dg::Elliptic< Matrix, Vector, Preconditioner >", "classdg_1_1_elliptic.html", null ],
    [ "exception", null, [
      [ "dg::Fail", "structdg_1_1_fail.html", null ],
      [ "dg::KeineNST_1D", "classdg_1_1_keine_n_s_t__1_d.html", null ],
      [ "dg::NotANumber", "structdg_1_1_not_a_number.html", null ],
      [ "dg::Ooops", "structdg_1_1_ooops.html", null ]
    ] ],
    [ "dg::EXP< T >", "structdg_1_1_e_x_p.html", null ],
    [ "dg::ExpProfX", "structdg_1_1_exp_prof_x.html", null ],
    [ "dg::Gaussian", "structdg_1_1_gaussian.html", null ],
    [ "dg::Gaussian3d", "structdg_1_1_gaussian3d.html", null ],
    [ "dg::GaussianX", "structdg_1_1_gaussian_x.html", null ],
    [ "dg::GaussianY", "structdg_1_1_gaussian_y.html", null ],
    [ "dg::GaussianZ", "structdg_1_1_gaussian_z.html", null ],
    [ "dg::GeneralElliptic< Matrix, Vector, Preconditioner >", "structdg_1_1_general_elliptic.html", null ],
    [ "dg::Helmholtz< Matrix, Vector, Preconditioner >", "structdg_1_1_helmholtz.html", null ],
    [ "dg::Histogram< container >", "structdg_1_1_histogram.html", null ],
    [ "dg::Histogram2D< container >", "structdg_1_1_histogram2_d.html", null ],
    [ "dg::Invert< container >", "structdg_1_1_invert.html", null ],
    [ "dg::Karniadakis< Vector >", "structdg_1_1_karniadakis.html", null ],
    [ "dg::Lamb", "structdg_1_1_lamb.html", null ],
    [ "dg::LHalf", "structdg_1_1_l_half.html", null ],
    [ "dg::LinearX", "structdg_1_1_linear_x.html", null ],
    [ "dg::LinearY", "structdg_1_1_linear_y.html", null ],
    [ "dg::LN< T >", "structdg_1_1_l_n.html", null ],
    [ "dg::MinMod< T >", "structdg_1_1_min_mod.html", null ],
    [ "dg::MOD< T >", "structdg_1_1_m_o_d.html", null ],
    [ "dg::PLUS< T >", "structdg_1_1_p_l_u_s.html", null ],
    [ "dg::Poisson< Matrix, container >", "structdg_1_1_poisson.html", null ],
    [ "dg::RHalf", "structdg_1_1_r_half.html", null ],
    [ "dg::RK< k, Vector >", "structdg_1_1_r_k.html", null ],
    [ "dg::rk_coeff< k >", "structdg_1_1rk__coeff.html", null ],
    [ "dg::SinProfX", "structdg_1_1_sin_prof_x.html", null ],
    [ "dg::SIRK< Vector >", "structdg_1_1_s_i_r_k.html", null ],
    [ "dg::SQRT< T >", "structdg_1_1_s_q_r_t.html", null ],
    [ "dg::Vortex", "structdg_1_1_vortex.html", null ]
];